package com.crud.model;

import javax.validation.constraints.Pattern;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.emp_id
     *
     * @mbg.generated Sat Feb 01 01:39:37 CST 2020
     */
    private Integer empId;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.emp_gender
     *
     * @mbg.generated Sat Feb 01 01:39:37 CST 2020
     */
    private String empGender;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.emp_name
     *
     * @mbg.generated Sat Feb 01 01:39:37 CST 2020
     */

    @Pattern(regexp="(^[a-zA-Z0-9-_]{6,16}$)|(^[\\u2e80-\\u9fff]{2,5})"
            ,message= "用户名必须是6~16位数字和字母的组合，或者2~5位中文")
    private String empName;


    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.email
     *
     * @mbg.generated Sat Feb 01 01:39:37 CST 2020
     */
    @Pattern(regexp="^([a-z0-9_\\.-]+)@([\\da-z\\.-]+)\\.([a-z\\.]{2,6})$",
            message ="邮箱格式不正确，请重新输入！")
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp.d_id
     *
     * @mbg.generated Sat Feb 01 01:39:37 CST 2020
     */

    private Integer dId;

   private Department department;

    /*新增部门信息*/

    public Employee() {
        super();
    }



    public Employee(Integer empId, String empName, String empGender, String email, Integer dId) {
        this.empId = empId;
        this.empName = empName;
        this.empGender = empGender;
        this.email = email;
        this.dId = dId;

    }

    public Employee(Integer empId, String empName, String empGender, String email, Integer dId, Department department) {
        this.empId = empId;
        this.empName = empName;
        this.empGender = empGender;
        this.email = email;
        this.dId = dId;
        this.department = department;
    }

    public Department getDepartment() {
        return department;
    }

    public void setDepartment(Department department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.emp_id
     *
     * @return the value of emp.emp_id
     *
     * @mbg.generated Sat Feb 01 01:39:37 CST 2020
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.emp_id
     *
     * @param empId the value for emp.emp_id
     *
     * @mbg.generated Sat Feb 01 01:39:37 CST 2020
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.emp_name
     *
     * @return the value of emp.emp_name
     *
     * @mbg.generated Sat Feb 01 01:39:37 CST 2020
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.emp_name
     *
     * @param empName the value for emp.emp_name
     *
     * @mbg.generated Sat Feb 01 01:39:37 CST 2020
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.emp_gender
     *
     * @return the value of emp.emp_gender
     *
     * @mbg.generated Sat Feb 01 01:39:37 CST 2020
     */
    public String getEmpGender() {
        return empGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.emp_gender
     *
     * @param empGender the value for emp.emp_gender
     *
     * @mbg.generated Sat Feb 01 01:39:37 CST 2020
     */
    public void setEmpGender(String empGender) {
        this.empGender = empGender == null ? null : empGender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp.email
     *
     * @return the value of emp.email
     *
     * @mbg.generated Sat Feb 01 01:39:37 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp.email
     *
     * @param email the value for emp.email
     *
     * @mbg.generated Sat Feb 01 01:39:37 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    public Integer getdId() {
        return dId;
    }

    public void setdId(Integer dId) {
        this.dId = dId;
    }

    @Override
    public String toString() {
        return "Employee{" +
                "empId=" + empId +
                ", empName='" + empName + '\'' +
                ", empGender='" + empGender + '\'' +
                ", email='" + email + '\'' +
                ", dId=" + dId +
                ", dept=" + department +
                '}';
    }
}